services:
  db:
    restart: unless-stopped
    image: postgres:15
    environment:
      POSTGRES_USER: miniflux
      POSTGRES_PASSWORD: 2014
      POSTGRES_DB: miniflux
    volumes:
      - db_data:/var/lib/postgresql/data
  miniflux:
    restart: unless-stopped
    image: miniflux/miniflux:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://miniflux:2014@db/miniflux?sslmode=disable
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=2014
    depends_on:
      - db
volumes:
  db_data:
